
temp_struct=cell(3,1);
test_spots=cell(3,1);

tic
parfor (i=1:3)
[temp_struct{i} test_spots{i}]=MakeSNPCalls(HIV_REF,bkg_data,...
    'alignments',ALL_ALIGNMENTS,...
    'pat_struct_input',test_PAT_STRUCT,...
    'hidden',rand(size(test_PAT_STRUCT))>0.8,...
    'use_distributed',false,...
    'pat_struct_out',true,...
    'nested',true,...
    'no_translate',true,...
    'force snp_spots',true);
end
toc

temp_struct
test_spots


temp_struct=cell(3,1);
test_spots=cell(3,1);


tic
for (i=1:3)
[temp_struct{i} test_spots{i}]=MakeSNPCalls(HIV_REF,bkg_data,...
    'alignments',ALL_ALIGNMENTS,...
    'pat_struct_input',test_PAT_STRUCT,...
    'hidden',rand(size(test_PAT_STRUCT))>0.8,...
    'use_distributed',false,...
    'pat_struct_out',true,...
    'nested',true,...
    'no_translate',true,...
    'force snp_spots',true);
end
toc


